name: ci_dockerfile
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, debian-10, centos-8, fedora-31]
        include:
          - os: ubuntu-18.04
            family: ubuntu
            version: 18.04
          - os: ubuntu-20.04
            family: ubuntu
            version: 20.04
          - os: debian-10
            family: debian
            version: 10
          - os: centos-8
            family: centos
            version: 8
          - os: fedora-31
            family: fedora
            version: 31
    steps:
      - uses: actions/checkout@master
      - name: buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: docker login
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username fastide --password-stdin
      - name: docker build
        run: |
          docker buildx build \
              -t fastide/toolbox-${{ matrix.family }}:${{ matrix.version  }} \
              --platform=linux/amd64,linux/386,linux/arm64 \
              --build-arg OS_FAMILY=${{ matrix.family }} \
              --build-arg OS_VERSION=${{ matrix.version  }} \
              --push .
